name: HotbarRemover
version: '1.0-SNAPSHOT'
main: org.maseunknown.plugins.hotbarremover.HotbarRemover
api-version: '1.20'
commands:
  hotbarremover:
    description: start command for all commands
    usage: /<command>